### ISSUE TITLE
Duidelijke structuur aan je applicatie

### ISSUE THREAD

**Issue by MelvinIdema** [randy554/frontend-applications-21-22#35]
Je hebt een duidelijke structuur aan je applicatie gegeven! Het laat echt zien dat je al een goed begrip hebt van React als framework en een duidelijk idee hebt van je doelen en wensen dit project. Je hebt veel van de behandelde stof toegepast op een manier die laat zien dat je een diep begrip hebt van de stof.

**Comment by randy554** [comment]
Thanks man
